name: Go

on: [push]

jobs:
  build:

    runs-on: windows-2022
    strategy:
      matrix:
        go-version: [ '1.20.4' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test